@startuml

package controller{
    class GameController{
        +<<Create>>GameController(game : Game)
        + placeFlyingTile(pos : Position)
        + rotateFlyingTile()
        + move(direction : Direction)
        + nextTurn()
        + captureObjective()
        + finishGame()
    }
}

package model{

    enum Direction << enumeration >> {
        UP
        RIGHT
        DOWN
        LEFT
    }

    interface PlateauObserver{
        + {abstract}movePlayer(oldPos : Position , newPos : Position , path : String )

    }


    class Game{
        - m_currentPlayer : Integer
        - m_insertedFlyingTile : Boolean

        +<<Create>>Game()
        - distributeObjectivesToPlayer(lstObj : Objective[])
        + getPlayer(player : Integer) : Player
        - initPlayers()
        - placePlayer()
        + getGameBoard() : GameBoard
        + getCurrentPlayer() : Player
        + insertFlyingTile(pos : Position)
        - getCurrentPlayerPosition() : Position
        + movePlayer(direction : Direction)
        + nextTurn()
        + captureObjective()
        + finishGame()
    }

    class GameBoard{
        +<<Create>>GameBoard()
        + addObserver(obs : PlateauObserver)
        + removeObserver(obs : PlateauObserver)
        + notifyObserverTiles(pos : Position)
        + notifyObserverEndGame()
        + getFlyTile() : Tiles
        + getGameBoard() : Tiles[][]
        + getTile(pos : Position) : Tiles
        - initObjective()
        - initTuiles()
        - initGameBoard()
        + insertFlyingTile(pos : Position)
        - placeTileOnGameBoardInit(pos : Position, tiles : Tiles)
        - initPlaceTuileT()
        - initPlaceTuileAng()
        - placerTuile()
        + inBoard(pos : Position) : Boolean
        + getTile(pos : Position) : Tiles
        + outSideBoard(pos : Position) : Position
        - placeObjective()
        + getLstObjective() : ArrayList<Objective>
    }

    class Objective{
        - m_path : String
        - m_name : String

        +<<Create>>Objective(name : String)
        +<<Create>>Objective(name : String, path : String)
        + getNameObjectif() : String
        + getPath() : String
    }

    class Pawn{
        - m_path : String


        +<<Create>>Pawn(path : String, position : Position)
        + setPath(path : String)
        + getPath() : String
        + setPosition(position : Position)
        + getPosition() : Position
        + toStr()
        + setStartPosition(pos : Position)
        + getStartPosition() : Position
    }

    interface GameBoardObserver{
        + updateTile(pos : Position)
        + endGame()
    }

    class Player{
        - m_name : String
        - m_objectiveCapture : Integer

        +<<Create>>Player(name : String)
        + addObserver(obs : PlayerObserver)
        + removeObserver(obs : PlayerObserver)
        + notifyObserver(oldPos : Position, newPos : Position)
        + setLstObjective(lstObjective : ArrayList<Objective>)
        + getLstObjective() : ArrayList<Objective>
        + getPosition() : Position
        + getPositionX() : Integer
        + getPositionY() : Integer
        + move(pos : Position)
        + setImgPawn(path : String)
        + getImgPawn() : String
        + setPawnPosition(pos : Position)
        + captureObjective(obj : Objective)
        + allObjectiveCapture() : Boolean
        + isStartPos(pos : Position) : Boolean
        + getPath() : String
        + toString() : String
        + setStartPos(pos : Position)
        + getStartPos() : Position
    }

    interface PlayerObserver{
        + movePlayer(oldPos : Position, newPos : Position, path : String)
    }

    interface TilesObserver{
        +    updateRotateTile(tile : Tiles )

    }

    class Position{
        - m_x : Integer
        - m_y : Integer

        +<<Create>>Position(x : Integer, y : Integer)
        + setPositionX(x : Integer)
        + setPositionY(y : Integer)
        + getPositionX() : Integer
        + getPositionY() : Integer
        + moveRight() : Position
        + moveLeft() : Position
        + moveUp() : Position
        + moveDown() : Position
        + generateRandomPosition(maxX : Integer, maxY : Integer) : Position
    }

    abstract Tiles{
        - m_openDirections : Boolean[4]
        - m_rotateIndex : Integer

        +<<Create>>Tiles(up : Boolean, right : Boolean, bottom : Boolean, left : Boolean)
        +<<Create>>Tiles(objective : Objective, up : Boolean, right : Boolean, bottom : Boolean, left : Boolean)
        + addObserver(observer : TilesObserver)
        + removeObserver(observer : TilesObserver)
        + notifyObserver()
        + getOpen(direction : Direction) : Boolean
        + rotateClockWise()
        + rotateClockWise(n : Integer)
        + {abstract}getPath() : String
        + getRotateIndex() : Integer
        + moveTile(direction : Direction, tile : Tiles) : Boolean
        + toStrPossibilite()
        + setObjective(obj : Objective)
        + getObjective() : Objective
        + {abstract}setPath(path : String)
    }

    class TilesCorner extends Tiles{
        - m_pathTileCorner : String

        +<<Create>>TilesCorner()
        +<<Create>>TilesCorner(objective : Objective)
        + getPath() : String
        + setPath(path : String)
    }

    class TilesLinear extends Tiles{
        - m_pathTileLinear : String

        +<<Create>>TilesLinear()
        +<<Create>>TilesLinear(objective : Objective)
        + getPath() : String
        + setPath(path : String)
    }

    class TilesT extends Tiles{
        - m_pathTileT : String

        +<<Create>>TilesT()
        +<<Create>>TilesT(objective : Objective)
        + getPath() : String
        + setPath(path : String)
    }

    class TuileFactory{
        +<<Create>>TuileFactory()
        + createTileLinear() : TilesLinear
        + createTileLinear(objective : Objective) : TilesLinear
        + createTileCorner() : TilesCorner
        + createTileCorner(objective : Objective) : TilesCorner
        + createTileT() : TilesT
        + createTileT(objective : Objective) : TilesT
    }

}

package view{
    class BackgroundPanel{
        - m_backgroundImage : BufferedImage
        - m_darknessFactor : Float

        +<<Create>>BackgroundPanel(backgroundImage : BufferedImage)
        #paintComponent(g : Graphics)
    }

    class ControlPanel extends JComponent{
        - m_btnHaut : TransparentJButton
        - m_btnBas : TransparentJButton
        - m_btnGauche : TransparentJButton
        - m_btnDroite : TransparentJButton

        +<<Create>>ControlPanel(controller : GameController)
    }

    class GameBoardPanel extends JPanel implements model.PlayerObserver{

        +<<Create>>GameBoardPanel(gameBoard : GameBoard)
        + placePawn(player : Player)
        + initTuilesComponents()
        + getFlyingTileComponent() : TuileComponent
        + updateGameBoard(pos : Position)
        + movePlayer(oldPos : Position, newPos : Position, path : String)
        + updateTile(pos : Position)
        + actualizePlayer(player : Player, path : String)
    }

    class GameDisplay extends JFrame implements model.GameBoardObserver{
        - m_mainPanel : JPanel
        - m_buttonSection : JPanel
        - m_flyingTilePanel : JPanel
        - m_colorRotation : Integer
        - m_objectivePanel : JPanel

        +<<Create>>GameDisplay(game : Game, gameBoardPanel : GameBoardPanel)
        - initializeFrame()
        - initializeMainPanel()
        - initializePlateauPanel(gameBoardPanel : GameBoardPanel)
        - initializeControlPanel()
        - generateButtons()
        - initializeButtonSection()
        - createCaptureButton()
        - createNextTurnButton()
        - placePawns()
        - generateButtonLeft()
        - generateButtonRight()
        - generateButtonTop()
        - generateButtonBottom()
        - generateFlyingTilePlace()
        - updateObjectivePanel()
        - showObjective()
        - updateFlyingTile()
        - endGame()
        + updateTile(pos : Position)
    }

    class ImageHelper{
        + merge(backgroundPath : String, foregroundPaths : String[]) : BufferedImage
        + merge(background : BufferedImage, foregroundPaths : String[]) : BufferedImage
        + rotate(original : BufferedImage, angle : Double) : BufferedImage
        + rotateClockwise(original : BufferedImage) : BufferedImage
        + rotateCounterClockwise(original : BufferedImage) : BufferedImage
        + getPathImg(path : String) : List<String>
        + loadImage(imagePath : String) : BufferedImage
        + resizeImage(originalImage : BufferedImage, targetWidth : Integer, targetHeight : Integer) : BufferedImage
    }

    class ObjectiveComponent extends JComponent{
        - m_image : BufferedImage

        +<<Create>>ObjectiveComponent(objective : Objective)
        #paintComponent(g : Graphics)
        + setObjective(objective : Objective)
        + setImage(image : BufferedImage)
        + getImage() : BufferedImage
    }

    class TransparentJButton extends JButton{
        +<<Create>>TransparentJButton(text : String)
        #paintComponent(g : Graphics)
    }

    class TransparentPanel extends JPanel{
        +<<Create>>TransparentPanel()
        #paintComponent(g : Graphics)
    }

    class TuileComponent extends JComponent implements model.TilesObserver{
        - m_image : BufferedImage

        +<<Create>>TuileComponent(tiles : Tiles)
        #paintComponent(g : Graphics)
        + setTile(tiles : Tiles)
        + setImage(image : BufferedImage)
        + getImage() : BufferedImage
        + updateRotateTile(tile : Tiles)
    }

}

class LabyrintheApp{
    + main(args : String[])
}


controller.GameController           "1" *-[#595959,plain]-> "m_game\n1" Game
controller.GameController --[dashed]--> model.Position : <<uses>>
controller.GameController --[dashed]--> model.Direction : <<uses>>

model.Game  "1" *-[#595959,plain]-> "lstPlayer\n4" model.Player
model.Game  "1" *-[#595959,plain]-> "m_gameBoard\n1" model.GameBoard
model.Game --[dashed]--> model.Objective : <<uses>>
model.Game --[dashed]--> model.Position : <<uses>>
model.Game --[dashed]--> model.Direction : <<uses>>

model.GameBoard  "1" o-[#595959,plain]-> "m_lstTuilesGameBoard\n[49]" model.Tiles
model.GameBoard  "1" *-[#595959,plain]-> "m_StackCorner\n[*]" model.TilesCorner
model.GameBoard  "1" *-[#595959,plain]-> "m_stackT\n[*]" model.TilesT
model.GameBoard  "1" *-[#595959,plain]-> "m_stackLinear\n[*]" model.TilesLinear
model.GameBoard  "1" o-[#595959,plain]-> "m_lstObjective\n[*]" model.Objective
model.GameBoard  "1" o-[#595959,plain]-> "m_flyingTile\n" model.Tiles
model.GameBoard  "1" *-[#595959,plain]-> "m_lstObserver\n" model.PlateauObserver
model.GameBoard --[dashed]--> model.PlateauObserver : <<uses>>
model.GameBoard --[dashed]--> model.Position : <<uses>>


model.Pawn  "1" o-[#595959,plain]-> "m_position\n" model.Position
model.Pawn  "1" o-[#595959,plain]-> "m_startPosition\n" model.Position
model.Pawn --[dashed]--> model.Position : <<uses>>

model.GameBoardObserver --[dashed]--> model.Position : <<uses>>

model.Player  "1" *-[#595959,plain]-> "m_pawn\n" model.Pawn
model.Player  "1" *-[#595959,plain]-> "m_lstObserver\n[*]" model.PlayerObserver
model.Player  "1" *-[#595959,plain]-> "m_lstObjective\n[*]" model.Objective

model.Player --[dashed]--> model.Position : <<uses>>
model.Player --[dashed]--> model.PlayerObserver : <<uses>>

model.PlayerObserver --[dashed]--> model.Position : <<uses>>

model.Tiles  "1" *-[#595959,plain]-> "m_position\n" model.Position
model.Tiles  "1" *-[#595959,plain]-> "m_objective\n" model.Objective
model.Tiles  "1" *-[#595959,plain]-> "m_observers\n[*]" model.TilesObserver

model.Tiles --[dashed]--> model.TilesObserver : <<uses>>
model.Tiles --[dashed]--> model.Direction : <<uses>>

model.TilesCorner --[dashed]--> model.Objective : <<uses>>
model.TilesLinear --[dashed]--> model.Objective : <<uses>>
model.TilesT --[dashed]--> model.Objective : <<uses>>

model.TuileFactory --[dashed]--> model.TilesT : <<uses>>
model.TuileFactory --[dashed]--> model.TilesCorner : <<uses>>
model.TuileFactory --[dashed]--> model.TilesLinear : <<uses>>
model.TuileFactory --[dashed]--> model.Objective : <<uses>>

view.ControlPanel  "1" *-[#595959,plain]-> "m_controller \n" controller.GameController
view.ControlPanel --[dashed]--> controller.GameController : <<uses>>

view.GameBoardPanel  "1" *-[#595959,plain]-> "m_gameBoard\n" model.GameBoard
view.GameBoardPanel  "1" *-[#595959,plain]-> "m_tilesComponent\n[49]" view.TuileComponent
view.GameBoardPanel --[dashed]--> model.Player : <<uses>>
view.GameBoardPanel --[dashed]--> model.GameBoard : <<uses>>
view.GameBoardPanel --[dashed]--> model.Position : <<uses>>

view.GameDisplay  "1" *-[#595959,plain]-> "m_gameBoardPanel\n" view.GameBoardPanel
view.GameDisplay  "1" *-[#595959,plain]-> "m_game\n" model.Game
view.GameDisplay  "1" *-[#595959,plain]-> "m_gameController\n" controller.GameController

view.GameDisplay --[dashed]--> model.Game : <<uses>>
view.GameDisplay --[dashed]--> view.GameBoardPanel : <<uses>>
view.GameDisplay --[dashed]--> model.Position : <<uses>>

view.ObjectiveComponent  "1" *-[#595959,plain]-> "m_objective\n" model.Objective
view.ObjectiveComponent --[dashed]--> model.Objective : <<uses>>

view.TuileComponent  "1" *-[#595959,plain]-> "m_tiles\n" model.Tiles
view.TuileComponent --[dashed]--> model.Tiles : <<uses>>



@enduml